const DynamicItems = {
  'default': require(`../../assets/splash.png`),
  'splash': require(`../../assets/splash.png`),
  'test1': require(`../../assets/test_img/cat.png`),
  'test2': require(`../../assets/test_img/lion.png`),
  // -------------store itme----------------------------
  'animal1' : require(`../../assets/itemlist/field1.png`),
  'animal2' : require('../../assets/itemlist/animal2.png'),
  'animal4' : require('../../assets/itemlist/animal4.png'),
  'field1' : require('../../assets/itemlist/field1.png'),
  'field2' : require('../../assets/itemlist/field2.png'),
  'field3' : require('../../assets/itemlist/field3.png'),
  'field4' : require('../../assets/itemlist/field4.png'),
  'flower1' : require('../../assets/itemlist/flower1.png'),
  'house1' : require('../../assets/itemlist/house1.png'),
  'house2' : require('../../assets/itemlist/house2.png'),
  'house3' : require('../../assets/itemlist/house3.png'),
  'house4' : require('../../assets/itemlist/house4.png'),
  'house6' : require('../../assets/itemlist/house6.png'),
  'house7' : require('../../assets/itemlist/house7.png'),
  'house8' : require('../../assets/itemlist/house8.png'),
  'house9' : require('../../assets/itemlist/house9.png'),
  'house10' : require('../../assets/itemlist/house10.png'),
  'house11' : require('../../assets/itemlist/house11.png'),
  'stock1' : require('../../assets/itemlist/stock1.png'),
  'stock2' : require('../../assets/itemlist/stock2.png'),
  'stock3' : require('../../assets/itemlist/stock3.png'),
  'stock4' : require('../../assets/itemlist/stock4.png'),
  'stock6' : require('../../assets/itemlist/stock6.png'),
  'tree1' : require('../../assets/itemlist/tree1.png'),
  'waterfield1' : require('../../assets/itemlist/waterfield1.png'),
  'waterfield2' : require('../../assets/itemlist/waterfield2.png'),
  'waterfield3' : require('../../assets/itemlist/waterfield3.png'),
  'waterfield4' : require('../../assets/itemlist/waterfield4.png'),
  // -------------------secret item------------------------
  'animal3' : require('../../assets/itemlist/animal3.png'),
  'field5' : require('../../assets/itemlist/field5.png'),
  'house5' : require('../../assets/itemlist/house5.png'),
  'house12' : require('../../assets/itemlist/house12.png'),
  'stock5' : require('../../assets/itemlist/stock5.png'),
  'waterfield5' : require('../../assets/itemlist/waterfield5.png'),
}
// {
//   "default": "require('../../assets/splash.png')",
//   "voidforest": "require(`../../assets/splash.png`)",
//   "test1": "require(`../../assets/test_img/cat.png`)",
//   "test2": "require(`../../assets/test_img/lion.png`)"
// }
export default DynamicItems